version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - local-network
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local-network

  redis:
    image: redis/redis-stack
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - local-network

#   app:
#     restart: unless-stopped
#     build:
#       context: ./courier-tracking
#       dockerfile: Dockerfile
#     container_name: nest-docker
#     environment:
#       - PORT=3000
#     ports:
#       - '3000:3000'
#     depends_on:
#       - redis
#       - rabbitmq
#       - mongodb
#     volumes:
#       - ./src:/app/src
#     networks:
#       - local-network

networks:
  local-network:
    driver: bridge
volumes:
  mongodb_data_container:
