version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
      
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  # api: 
  #   build: .
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   command: npm run start:dev
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongodb
        # - rabbitmq
        # - redis

volumes:
  mongodb_data_container:
